--
  - hosts: all
    become: yes
    roles:
  - common


  - hosts: masters
    become: yes
    roles:
    - zookeeper
    - mesos-master
    - spark

  - hosts: workers
    become: yes
    roles:
    - mesos-worker
    - kafka
    - cassandra
